# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.linspace() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Modulo <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Floor Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Broadcasting <br>
  &nbsp;&nbsp;&nbsp;&nbsp; f) Indexing and Assigning NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Numpy Subsetting <br>
  &nbsp;&nbsp;&nbsp;&nbsp; h) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing White Sox Hitting Numbers <br>

<p>Python Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [1]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1, 2, 3]
l_2 = [4, 5, 6]

print(f"Summation of a regular python list: {l_1 + l_2}")
print(f"Difference of a regular python list: {l_1 - l_2}")

Summation of a regular python list: [1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

In [2]:
def sum_lists(l1, l2):
    output = []
    for idx in range(len(l1)):
        output.append(l1[idx] + l2[idx])
    return output
    
sum_lists([2, 3, 4], [1, 5, 2])

[3, 8, 6]

In [3]:
sum_lists(l_1, l_2)

[5, 7, 9]

In [4]:
x = [[1, 2, 3], [4, 5, 6]]
y = [[10, 20, 30], [14, 15, 16]]

sum_lists(x, y)

[[1, 2, 3, 10, 20, 30], [4, 5, 6, 14, 15, 16]]

## Numpy <br>

<p>NumPy is the fundamental package for scientific computing in Python. It is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. </p>
<a href="https://numpy.org/doc/stable/index.html" target="_blank" rel="noopener">Numpy Documentation</a>


#### Importing

In [5]:
# always import as np, standard across all of data science
# !pip install numpy
import numpy as np

In [6]:
np

<module 'numpy' from 'C:\\Users\\bstan\\anaconda3\\envs\\intro\\lib\\site-packages\\numpy\\__init__.py'>

<p>NumPy allows us to create arrays and manipulate numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be the same. NumPy arrays are faster and more compact than Python lists. A NumPy array consumes less memory and uses much less memory to store data.</p>

#### Creating an NDArray
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [7]:
# np.array([list])

arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))
arr1

[1 2 3]
<class 'numpy.ndarray'>


array([1, 2, 3])

In [8]:
arr2 = np.array([4, 5, 6])
arr2

array([4, 5, 6])

In [9]:
arr3 = np.array([7, 8, '9'])
arr3

array(['7', '8', '9'], dtype='<U11')

In [10]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

###### - np.zeros()

In [11]:
# np.zeros(shape)
# shape = the shape of the ndarray - int or tuple(RxC)
arr_zeros1 = np.zeros(5)
arr_zeros1

array([0., 0., 0., 0., 0.])

In [12]:
arr_zeros2 = np.zeros((5,3))
arr_zeros2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [13]:
# np.ones(shape)
arr_ones1 = np.ones(5)
arr_ones1

array([1., 1., 1., 1., 1.])

In [14]:
arr_ones2 = np.ones((5,3))
arr_ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###### - np.arange()

In [15]:
# np.arange(stop)
# np.arange(start, stop)
# np.arange(start, stop, step)

arr_range1 = np.arange(10)
arr_range1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr_range2 = np.arange(10,20)
arr_range2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
arr_range3 = np.arange(10,20,2)
arr_range3

array([10, 12, 14, 16, 18])

###### - np.linspace()

In [18]:
# np.linspace(start, stop, interval)

arr_lin = np.linspace(0,10, 5)
arr_lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
arr_lin2 = np.linspace(0,100,11)
arr_lin2

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

#### Performing Calculations on NDArrays

###### - Summation

In [20]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

result_sum = arr_list1 + arr_list2
result_sum

array([15, 30, 45, 60, 75])

###### - Difference

In [21]:
result_diff = arr_list2 - arr_list1
result_diff

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [22]:
result_mul = arr_list1 * arr_list2
result_mul

array([  50,  200,  450,  800, 1250])

###### - Division

In [23]:
result_div = arr_list2 / arr_list1
result_div

array([2., 2., 2., 2., 2.])

#### Modulo

In [24]:
result_mod = arr_list2 % arr_list1
result_mod

array([0, 0, 0, 0, 0], dtype=int32)

#### Floor Division

In [25]:
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2], dtype=int32)

#### Broadcasting

In [26]:
arr_list1

array([ 5, 10, 15, 20, 25])

In [27]:
arr_list1 * 5

array([ 25,  50,  75, 100, 125])

In [28]:
arr_list1 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

#### Concatenate

In [29]:
# np.concatenate((nda1, nda2))
arr_list3 = np.concatenate((arr_list1, arr_list2))
arr_list3

array([ 5, 10, 15, 20, 25, 10, 20, 30, 40, 50])

#### Indexing Numpy Arrays

In [30]:
arr_idx = np.arange(10)
arr_idx

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr_idx[2]

2

In [32]:
arr_idx[2:5]

array([2, 3, 4])

In [33]:
arr_idx[4:]

array([4, 5, 6, 7, 8, 9])

In [34]:
arr_idx[:6]

array([0, 1, 2, 3, 4, 5])

In [35]:
arr_idx[2:9:3]

array([2, 5, 8])

In [36]:
arr_idx[-3]

7

<p>But what happens when we have a multidimensional array?</p>

In [37]:
multi_list = [
    [23, 65, 43],
    [67, 82, 55],
    [90, 37, 12]
]

nd_m = np.array(multi_list)
nd_m

array([[23, 65, 43],
       [67, 82, 55],
       [90, 37, 12]])

Similar to lists within lists. It, however, looks more like the C-programming syntax...

In [38]:
# arr_name[row_index, col_index]

nd_m[1, 1]

82

In [39]:
nd_m[1]

array([67, 82, 55])

In [40]:
nd_m[2, 0]

90

#### Assigning Values

In [41]:
# arr_name[idx] = val OR arr_name[row_idx,col_idx] = val

arr_idx[3] = 100
arr_idx

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [42]:
nd_m[1,1] = 1
nd_m

array([[23, 65, 43],
       [67,  1, 55],
       [90, 37, 12]])

#### Numpy Subsetting

In [43]:
arr_sub = np.arange(0,900,150)
arr_sub

array([  0, 150, 300, 450, 600, 750])

In [44]:
print(arr_sub > 500)

[False False False False  True  True]


In [45]:
print(arr_sub[arr_sub > 500])

[600 750]


In [46]:
arr_sub[arr_sub % 100 == 0]

array([  0, 300, 600])

##### Multiple Filters

In [47]:
# arr_name[(first_condition) & OR | (second_condition)]
arr_sub[(arr_sub < 400) & (arr_sub % 100 == 0)]

array([  0, 300])

In [48]:
arr_sub[(arr_sub < 400) | (arr_sub % 100 == 0)]

array([  0, 150, 300, 600])

#### Checking NDArray Type

In [49]:
# usind the .dtype() method
nd_type = nd_m.dtype

nd_type

dtype('int32')

#### Altering NDArray Type

In [50]:
print(f"Type before change: {nd_m.dtype}")

changed = nd_m.astype(np.float32)

print(f"Type after change: {changed.dtype}")

Type before change: int32
Type after change: float32


In [51]:
changed

array([[23., 65., 43.],
       [67.,  1., 55.],
       [90., 37., 12.]], dtype=float32)

#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [52]:
 # shape is always rows x columns
# Checking the Shape of the nd_m Numpy Array
# Using the method .shape
print(nd_m.shape)
print(type(nd_m.shape))

(3, 3)
<class 'tuple'>


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [53]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

print(changed.reshape( (1,9)))


[[23. 65. 43. 67.  1. 55. 90. 37. 12.]]


In [54]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)
changed.reshape((9,1))

array([[23.],
       [65.],
       [43.],
       [67.],
       [ 1.],
       [55.],
       [90.],
       [37.],
       [12.]], dtype=float32)

#### In-Class Exercise #1 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrix of strings

In [55]:
# array([['0', '1', '2', '3'],
#        ['4', '5', '6', '7'],
#        ['8', '9', '10', '11'],
#        ['12', '13', '14', '15']], dtype='<U11')



#### Complex Indexing & Assinging

In [56]:
M = np.zeros((6,6))
print('Resetting Matrix')
print('Before Assignment: ')
print(M)

# Set every first element in each row to 1
M[:,0] = 1
print('\n After assigning 1 to first column:')
print(M)

# Set all elements in axis 3 to 5 (Excluding 5) to be equal to the number 5
M[2:5, :] = 5
print('\n After assigning 5 to the rows 3-5:')
print(M)

# reset the matrix back to 0
print('\n Reset to Zero')
M = M * 0
print(M)

# Set the second and third columns to a number == 2
M[:, 1:3] = 2
print('\n Assigning 2 to the second and third rows')
print(M)

# Creating a vector in numpy
x = np.arange(6)

# Reset the Matrix to 0
M *= 0

# Set the first row to that range of vector numbers we just created
M[0, :] = x
print('\n Assigning vector array x to the first axis in the Matrix')
print(M)

#################
# M[rows,columns]
#################

Resetting Matrix
Before Assignment: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 After assigning 1 to first column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

 After assigning 5 to the rows 3-5:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]

 Reset to Zero
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 Assigning 2 to the second and third rows
[[0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]]

 Assigning vector array x to the first axis in the Matrix
[[0. 1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [57]:
matrix1 = np.array([
    [10, 20, 30],
    [5, 10, 15],
    [1, 2, 3]
])

matrix1

array([[10, 20, 30],
       [ 5, 10, 15],
       [ 1,  2,  3]])

In [58]:
matrix2 = np.array([5, 10, 20])
matrix2

array([ 5, 10, 20])

In [59]:
print(matrix1.shape)
print(matrix2.shape)

(3, 3)
(3,)


In [60]:
result_matrix = matrix1 * matrix2
result_matrix

array([[ 50, 200, 600],
       [ 25, 100, 300],
       [  5,  20,  60]])

In [61]:
matrix3 = np.array([
    [1,2],
    [3,4]
])

matrix3

array([[1, 2],
       [3, 4]])

In [62]:
print(matrix3.shape)

(2, 2)


In [63]:
non_comp_shape = matrix1 * matrix3
non_comp_shape

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [64]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.1945621437208298
Here is a random number between 0 and 1 Million: 398201.41827860766
Here are 5 random numbers between 0 and 10: [3.89860357 3.19256771 9.24551806 4.18981656 0.80164342]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[0.16512139 9.66644825 3.47402285]
 [8.9868087  9.39962072 2.72181944]
 [2.81606367 1.19096064 5.25028477]]


In [65]:
# np.random.randint()

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.randint(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.randint(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.randint(0, 10, (3, 3)))

Here is a random number between 0 and 1 Million: 52025
Here are 5 random numbers between 0 and 10: [6 9 9 9 3]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[5 1 4]
 [5 5 6]
 [5 7 3]]


## Working With CSV's

#### Imports

In [66]:
import csv
from datetime import datetime

In [67]:
# Creating Function to open and read CSV data
def open_csv(filename, d = ','):
    # define an empty list to store data
    data = []
    
    with open(filename, encoding = 'utf-8') as mData:
        # use the csv reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        # Loop over info and append to data list
        for row in info:
            data.append(row)
    return data

whitesox_data = open_csv('whitesox_2021_hitting.csv')

print(whitesox_data)

[['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB'], ['1', 'C', 'Yasmani Grandal', '32', '93', '375', '279', '60', '67', '9', '0', '23', '62', '0', '0', '87', '82', '.240', '.420', '.520', '.939', '157', '145', '15', '3', '1', '5', '0'], ['2', '1B', 'José Abreu', '34', '152', '659', '566', '86', '148', '30', '2', '30', '117', '1', '0', '61', '143', '.261', '.351', '.481', '.831', '125', '272', '28', '22', '0', '10', '3'], ['3', '2B', 'Cesar Hernandez', '31', '53', '217', '194', '24', '45', '4', '0', '3', '15', '1', '1', '21', '45', '.232', '.309', '.299', '.608', '69', '58', '5', '1', '0', '1', '2'], ['4', 'SS', 'Tim Anderson', '28', '123', '551', '527', '94', '163', '29', '2', '17', '61', '18', '7', '22', '119', '.309', '.338', '.469', '.806', '118', '247', '5', '1', '0', '1', '1'], ['5', '3B', 'Yoan Moncada', '26', '144', '616', '520', '74', '137', '33', '1'

In [68]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

def open_csv_as_ndarray(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, names=FIELDS, dtype=DATATYPES, skip_header=1)
    return data


sox21 = open_csv_as_ndarray('whitesox_2021_hitting.csv')
sox21

array([( 1, b'C', b'Yasmani Grandal', 32,  93, 375, 279, 60,  67,  9, 0, 23,  62,  0, 0, 87,  82, 0.24 , 0.42 , 0.52 , 0.939, 157, 145, 15,  3, 1,  5, 0),
       ( 2, b'1B', b'Jos\xc3\xa9 Abreu', 34, 152, 659, 566, 86, 148, 30, 2, 30, 117,  1, 0, 61, 143, 0.261, 0.351, 0.481, 0.831, 125, 272, 28, 22, 0, 10, 3),
       ( 3, b'2B', b'Cesar Hernandez', 31,  53, 217, 194, 24,  45,  4, 0,  3,  15,  1, 1, 21,  45, 0.232, 0.309, 0.299, 0.608,  69,  58,  5,  1, 0,  1, 2),
       ( 4, b'SS', b'Tim Anderson', 28, 123, 551, 527, 94, 163, 29, 2, 17,  61, 18, 7, 22, 119, 0.309, 0.338, 0.469, 0.806, 118, 247,  5,  1, 0,  1, 1),
       ( 5, b'3B', b'Yoan Moncada', 26, 144, 616, 520, 74, 137, 33, 1, 14,  61,  3, 2, 84, 157, 0.263, 0.375, 0.412, 0.787, 117, 214,  6, 10, 0,  2, 1),
       ( 6, b'LF', b'Andrew Vaughn', 23, 127, 469, 417, 56,  98, 22, 0, 15,  48,  1, 1, 41, 101, 0.235, 0.309, 0.396, 0.705,  92, 165, 14,  6, 0,  5, 0),
       ( 7, b'CF', b'Luis Robert', 23,  68, 296, 275, 42,  93, 22, 1, 1

In [69]:
sox21['Name']

array([b'Yasmani Grandal', b'Jos\xc3\xa9 Abreu', b'Cesar Hernandez',
       b'Tim Anderson', b'Yoan Moncada', b'Andrew Vaughn', b'Luis Robert',
       b'Adam Eaton', b'Yermin Mercedes', b'Leury Garcia',
       b'Brian Goodwin', b'Eloy Jimenez', b'Zack Collins',
       b'Nick Madrigal', b'Danny Mendick', b'Gavin Sheets', b'Adam Engel',
       b'Billy Hamilton', b'Jake Lamb', b'Seby Zavala', b'Jake Burger',
       b'Romy Gonzalez', b'Nick Williams', b'Luis Gonzalez'], dtype='|S25')

In [70]:
sox21['H']

array([ 67, 148,  45, 163, 137,  98,  93,  38,  65, 111,  52,  53,  41,
        61,  36,  40,  31,  28,  24,  17,  10,   8,   0,   2], dtype=int32)

In [71]:
# Hitters who had more than 100 hits
sox21[sox21['H'] > 100]

array([( 2, b'1B', b'Jos\xc3\xa9 Abreu', 34, 152, 659, 566, 86, 148, 30, 2, 30, 117,  1, 0, 61, 143, 0.261, 0.351, 0.481, 0.831, 125, 272, 28, 22, 0, 10, 3),
       ( 4, b'SS', b'Tim Anderson', 28, 123, 551, 527, 94, 163, 29, 2, 17,  61, 18, 7, 22, 119, 0.309, 0.338, 0.469, 0.806, 118, 247,  5,  1, 0,  1, 1),
       ( 5, b'3B', b'Yoan Moncada', 26, 144, 616, 520, 74, 137, 33, 1, 14,  61,  3, 2, 84, 157, 0.263, 0.375, 0.412, 0.787, 117, 214,  6, 10, 0,  2, 1),
       (10, b'UT', b'Leury Garcia', 30, 126, 474, 415, 60, 111, 22, 4,  5,  54,  6, 2, 41,  97, 0.267, 0.335, 0.376, 0.711,  96, 156, 12,  4, 9,  5, 0)],
      dtype=[('Rk', '<i4'), ('Pos', 'S25'), ('Name', 'S25'), ('Age', '<i4'), ('G', '<i4'), ('PA', '<i4'), ('AB', '<i4'), ('R', '<i4'), ('H', '<i4'), ('2B', '<i4'), ('3B', '<i4'), ('HR', '<i4'), ('RBI', '<i4'), ('SB', '<i4'), ('CS', '<i4'), ('BB', '<i4'), ('SO', '<i4'), ('BA', '<f4'), ('OBP', '<f4'), ('SLG', '<f4'), ('OPS', '<f4'), ('OPS_1', '<i4'), ('TB', '<i4'), ('GDP', '<i4'), 

In [72]:
# Hitters who had less than 10 home runs
sox21[sox21['HR'] < 10][['Name','HR']]

array([(b'Cesar Hernandez', 3), (b'Adam Eaton', 5),
       (b'Yermin Mercedes', 7), (b'Leury Garcia', 5),
       (b'Brian Goodwin', 8), (b'Zack Collins', 4), (b'Nick Madrigal', 2),
       (b'Danny Mendick', 2), (b'Adam Engel', 7), (b'Billy Hamilton', 2),
       (b'Jake Lamb', 6), (b'Seby Zavala', 5), (b'Jake Burger', 1),
       (b'Romy Gonzalez', 0), (b'Nick Williams', 0),
       (b'Luis Gonzalez', 0)],
      dtype={'names':['Name','HR'], 'formats':['S25','<i4'], 'offsets':[29,86], 'itemsize':154})

In [73]:
# find total rbis
rbis = sox21['RBI']
print(rbis)
total_rbis = sum(sox21['RBI'])
print(total_rbis)

[ 62 117  15  61  61  48  43  28  37  54  29  37  26  21  20  34  18  11
  13  15   3   2   0   0]
755


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>